# Safety Security and License Configuration file
security:
  ignore-cvss-severity-below: 0
  ignore-cvss-unknown-severity: False
  ignore-vulnerabilities:
    70612:
      # CVE-2019-8341
      reason: its from safety
      expires: '2025-02-02'
  continue-on-vulnerability-error: False
