# Safety Security and License Configuration file
security:
  ignore-cvss-severity-below: 0
  ignore-cvss-unknown-severity: False
  ignore-vulnerabilities:
    62044:
      # CVE-2023-5752: https://data.safetycli.com/v/62044/f17/
      # Pip 23.3 includes a fix for CVE-2023-5752: When installing a package from a Mercurial VCS URL (ie "pip install hg+...") with pip...
      # PR: https://github.com/sqlalchemy/sqlalchemy/pull/8563
      reason: we don't use Mercurial VCS and don't use unsafe function
      expires: '2025-02-02'
  continue-on-vulnerability-error: False
